=== anna-hope/pylexemes/lexemes.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="lexemes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="lexeme" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="lang">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-z][a-z][a-z]"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="form" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== anna-hope/pylexemes/lexemes.brother.xml
<?xml version="1.0" encoding="UTF-8" ?>

<lexemes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lexemes.xsd">
	<lexeme>
		<lang>eng</lang>
		<form>broθor</form>
	</lexeme>

	<lexeme>
		<lang>rus</lang>
		<form>brat</form>
	</lexeme>
	
	<lexeme>
		<lang>got</lang>
		<form>broθar</form>
	</lexeme>

	<lexeme>
		<lang>grc</lang>
		<form>ɸrater</form>
	</lexeme>
	
	<lexeme>
		<lang>lat</lang>
		<form>frater</form>
	</lexeme>
	
	<lexeme>
		<lang>ave</lang>
		<form>bratar</form>
	</lexeme>
	
	<lexeme>
		<lang>non</lang>
		<form>broðir</form>
	</lexeme>
	
	<lexeme>
		<lang>xto</lang>
		<form>praçar</form>
	</lexeme>
	
	<lexeme>
		<lang>txb</lang>
		<form>proçer</form>
	</lexeme>
	
	<lexeme>
		<lang>sga</lang>
		<form>braθar</form>
	</lexeme>
	
	<lexeme>
		<lang>xpg</lang>
		<form>bratere</form>
	</lexeme>
</lexemes>
